---
name: Bug Report
about: Report a bug or an issue with Meteor Rejects
title: "[Bug] "
labels: bug
assignees: ''
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug?
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: input
    id: meteor-version
    attributes:
      label: Meteor Version
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true